apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsvcfront
  labels:
    app: microsvcfront

spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsvcfront
  template:
    metadata:
      labels:
        app: microsvcfront

    spec:
      containers:
      - name: microsvcfront
        image: microsvcfront:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888


